const fs = require('node:fs/promises');
const path = require('node:path');
const { JSDOM } = require('jsdom');
const { axios, version } = require('../services/axios.js');
const { escapeXml, normalizeUrl, calculatePriority } = require('../utils/xml.js');
const { logInfo, logSuccess, logError, logWarning, logInfoStart, logInfoAppend } = require('../utils/kleur.js');

const IGNORED_PATTERNS = ['cdn-cgi', '?referrer=', '&referrer=', '/signin/v2/usernamerecovery', '/lifecycle/flows/signup', 'join?return_to='];
const BASE_DELAY = 12000;
const MAX_URLS = 50000;

const shouldIncludeUrl = (url, baseUrl, baseOrigin, urlOrigin = null) => {
	if (!url.startsWith(baseUrl)) return false;
	if (IGNORED_PATTERNS.some(pattern => url.includes(pattern))) return false;
	try {
		return (urlOrigin ?? new URL(url).origin) === baseOrigin;
	} catch {
		return false;
	}
};

const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
const formatIso = date => date.toISOString().replace(/\.\d{3}Z$/, 'Z');
const nowIso = () => formatIso(new Date());

const fetchUrl = async (url, retries = 0) => {
	try {
		logInfoStart(`GET ${url}`);

		const res = await axios.get(url);
		if (res.status === 200) {
			return res;
		} else {
			process.stdout.write('\n');
			logWarning(`Non-200 status code (${res.status}) for URL: ${url}. Skipping...`);
			return null;
		}
	} catch (err) {
		process.stdout.write('\n');
		if (err.response) {
			const statusCode = err.response.status;
			if (statusCode === 429) {
				const delayTime = BASE_DELAY * (2 ** retries);
				logWarning(`429: Rate limit hit! Retrying in ${(delayTime / 1000).toFixed(2)}s... (Attempt ${retries + 1})`);
				await delay(delayTime);
				return fetchUrl(url, retries + 1);
			} else if (statusCode === 404) {
				logWarning('404: Not Found');
				return null;
			} else {
				logError(`${statusCode}: Failed to fetch! Skipping...`);
				return null;
			}
		} else {
			logError(`Failed to fetch ${url}. Unknown error: ${err.message}. Skipping...`);
			return null;
		}
	}
};

const crawl = async (startUrl, baseUrl, baseOrigin, visitedUrls) => {
	const queued = new Set();
	const queue = [];

	const enqueue = url => {
		if (!queued.has(url)) {
			queued.add(url);
			queue.push(url);
		}
	};

	enqueue(normalizeUrl(startUrl));

	while (queue.length > 0) {
		const normalizedUrl = queue.shift();

		const res = await fetchUrl(normalizedUrl);
		if (!res) continue;

		const dom = new JSDOM(res.data);
		const { document } = dom.window;

		const canonicalEl = document.querySelector('link[rel="canonical"]');
		if (canonicalEl) {
			try {
				const canonical = new URL(canonicalEl.getAttribute('href'), baseUrl);
				canonical.hash = '';
				if (canonical.href !== normalizedUrl && shouldIncludeUrl(canonical.href, baseUrl, baseOrigin, canonical.origin)) {
					logInfoAppend(`GET ${normalizedUrl} (canonical → ${canonical.href}, skipped)`);
					dom.window.close();
					enqueue(canonical.href);
					continue;
				}
			} catch {
				// ...
			}
		}

		const links = new Set();
		for (const link of document.querySelectorAll('a[href]')) {
			try {
				const resolved = new URL(link.getAttribute('href'), baseUrl);
				resolved.hash = '';
				if (shouldIncludeUrl(resolved.href, baseUrl, baseOrigin, resolved.origin)) links.add(resolved.href);
			} catch {
				// ...
			}
		}

		const rawLastMod = res.headers['last-modified']
			?? document.querySelector('meta[property="article:modified_time"]')?.getAttribute('content')
			?? document.querySelector('meta[name="last-modified"]')?.getAttribute('content');

		dom.window.close();

		const lastmodDate = rawLastMod ? new Date(rawLastMod) : new Date();
		visitedUrls.set(normalizedUrl, {
			url: normalizedUrl,
			lastmod: formatIso(lastmodDate),
			priority: calculatePriority(normalizedUrl, baseUrl),
		});

		logInfoAppend(`GET ${normalizedUrl} (${links.size} urls)`);

		for (const link of links) enqueue(link);
	}
};

const buildSitemapContent = urls => `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by https://github.com/sefinek/easy-sitemap-generator v${version} at ${nowIso()} -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
${urls.map(({ url, priority, lastmod }) => `    <url>
        <loc>${escapeXml(url)}</loc>
        <lastmod>${lastmod}</lastmod>
        <priority>${priority.toFixed(2)}</priority>
    </url>`).join('\n')}
</urlset>`;

const buildIndexContent = sitemapLocs => `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by https://github.com/sefinek/easy-sitemap-generator v${version} at ${nowIso()} -->
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapLocs.map(({ loc, lastmod }) => `    <sitemap>
        <loc>${escapeXml(loc)}</loc>
        <lastmod>${lastmod}</lastmod>
    </sitemap>`).join('\n')}
</sitemapindex>`;

const generate = async (baseUrl, destination = 'sitemap.xml') => {
	logInfo(`Starting crawl for base URL: ${baseUrl}`);

	const { origin: baseOrigin } = new URL(baseUrl);
	const visitedUrls = new Map();
	await crawl(baseUrl, baseUrl, baseOrigin, visitedUrls);

	logInfo(`Generating sitemap with ${visitedUrls.size} URLs...`);

	const urls = Array.from(visitedUrls.values())
		.filter(entry => entry.lastmod != null && entry.priority != null)
		.sort((a, b) => b.priority - a.priority);

	const output = path.resolve(destination);
	if (urls.length <= MAX_URLS) {
		const content = buildSitemapContent(urls);
		await fs.writeFile(output, content, 'utf8');
		logSuccess(`Sitemap generated at ${output}`);
		return content;
	}

	logWarning(`Found ${urls.length} URLs — exceeds the ${MAX_URLS} limit. Splitting into multiple sitemap files...`);

	const ext = path.extname(destination);
	const base = path.basename(destination, ext);
	const dir = path.dirname(output);
	const timestamp = nowIso();

	const totalParts = Math.ceil(urls.length / MAX_URLS);
	const sitemapLocs = [];
	for (let i = 0, part = 1; i < urls.length; i += MAX_URLS, part++) {
		const filename = `${base}-${part}${ext}`;
		const filepath = path.join(dir, filename);
		const content = buildSitemapContent(urls.slice(i, i + MAX_URLS));
		await fs.writeFile(filepath, content, 'utf8');
		logSuccess(`Sitemap part ${part}/${totalParts} written to ${filepath}`);
		sitemapLocs.push({ loc: `${baseOrigin}/${filename}`, lastmod: timestamp });
	}

	const indexContent = buildIndexContent(sitemapLocs);
	await fs.writeFile(output, indexContent, 'utf8');
	logSuccess(`Sitemap index written to ${output}`);

	return indexContent;
};

module.exports = { generate, version };
